name: End-to-end tests

on:
  push:
    branches:
      - "**"
      - "!master"

env:
  PG_USER: api-auth
  PG_PASSWORD: api-auth
  PG_DATABASE: api-auth-test
  PG_PORT: 5432
  MCP_HOST: http://localhost:3000

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      JWKS_PATH: "/tmp/jwks.json"
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:12.12
        env:
          POSTGRES_USER: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
          POSTGRES_DB: ${{ env.PG_DATABASE }}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - name: Install Cypress
        run: npm install cypress@12
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          wait-on: ${{ env.MCP_HOST }}/users/start-sign-in
          build: npm run build
          start: npm start
          install: false
        env:
          NODE_ENV: production
          ACCESS_LOG_PATH:
          PGUSER: ${{ env.PG_USER }}
          PGPASSWORD: ${{ env.PG_PASSWORD }}
          PGDATABASE: ${{ env.PG_DATABASE }}
          PGPORT: ${{ env.PG_PORT }}
          DATABASE_URL: postgres://${{ env.PG_USER }}:${{ env.PG_PASSWORD }}@127.0.0.1:${{ env.PG_PORT }}/${{ env.PG_DATABASE }}
          SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
          MONCOMPTEPRO_HOST: ${{ env.MCP_HOST }}
          DO_NOT_SEND_MAIL: "False"
          DO_NOT_VALIDATE_MAIL: "True"
          SESSION_COOKIE_SECRET: secret
          DEBOUNCE_API_KEY:
          SENTRY_DSN:
          INSEE_CONSUMER_KEY: ${{ secrets.INSEE_CONSUMER_KEY }}
          INSEE_CONSUMER_SECRET: ${{ secrets.INSEE_CONSUMER_SECRET }}
          CYPRESS_MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
          SECURE_COOKIES: "false"
      # Store tests runs in case of failure
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
